pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample-docker/pom.xml clean package'
            }
        }
    
        stage('Create Tomcat Docker Image'){
            steps {
                sh "pwd"
                sh "ls -a"
                sh "docker build ./java-tomcat-sample-docker -t tomcatsamplewebapp:${env.BUILD_ID}"
            }
        }
        stage("Creating Docker Container"){
            steps{
                sh "echo Creating container"
                sh "docker run -p 7070:8080 -d --name tomacatsamplecntnr tomcatsamplewebapp:${env.BUILD_ID}"
            }
        }

    }
}